name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # runs every day at midnight
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: vedantb23
          filename: github-metrics.svg
          base: header, activity
          plugin_languages: yes
